spring.datasource.url=jdbc:postgresql://localhost:5433/mydb2
spring.datasource.username=myuser2
spring.datasource.password=mypassword2
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# authentication
app.jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
app.jwt.expiration=86400000